export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_BURGER = "INIT_BURGER";
export const REPORT_ERROR = "REPORT_ERROR";
export const PURCHASING = "PURCHASING";
export const STOP_PURCHASING = "STOP_PURCHASING";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAILED";
export const PURCHASE_STARTED = "PURCHASE_STARTED";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOG_OUT = "LOG_OUT";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";